name: ai-caller

services:
  n8n:
    container_name: ai-caller-n8n
    image: docker.n8n.io/n8nio/n8n
    depends_on:
      - db
    networks:
      - db_network
    ports:
        - ${N8N_PORT}:5678
    environment:
      - GENERIC_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${DATABASE_NAME}
      - DB_POSTGRESDB_USER=${DATABASE_USERNAME}
      - DB_POSTGRESDB_PASSWORD=${DATABASE_PASSWORD}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_SCHEMA=n8n
    restart: unless-stopped

  db:
    container_name: ai-caller-db
    networks:
      - db_network
    image: postgres:18
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

networks:
  db_network:
