// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "bun" {
  interface Env {
    PORT: string;
    OPENAI_API_KEY: string;
    DATABASE_URL: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    CLIENT_URL: string;
    MAX_ROOM_CALL_DURATION_MINUTE: string
  }
}

declare global {
  namespace NodeJS {
    interface ProcessEnv extends Bun.Env { }
  }
}
